sudo: required
language: bash
env:
  global:
  - IMAGE_NAME=gableroux/unity3d:latest
  - BUILD_NAME=HallThrusterVisualization
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_66087b1c9a02_key -iv $encrypted_66087b1c9a02_iv
    -in Unity_v2019.x.ulf.enc -out ./Unity_v2019.x.ulf -d
    - export UNITY_LICENSE_CONTENT=`cat Unity_v2019.x.ulf`
    - rm Unity_v2019.x.ulf
    - docker pull $IMAGE_NAME
jobs:
  include:
  - stage: build
    env: BUILD_TARGET=StandaloneOSX
    script:
    - "chmod +x ./ci/* && ./ci/docker_build.sh"
    - "sudo chmod -R 777 ./Builds/"
    - "cd ./Builds/"
    - "zip -r StandaloneOSX.zip ./StandaloneOSX"
    deploy:
      provider: releases
      api_key: $GITHUB_API_KEY
      file: StandaloneOSX.zip
      skip_cleanup: true
      on:
        tags: true
